use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ContractError {
    AdminNotFound = 91,
    RegistryNotFound=93,
    InvalidSignature = 99,
    // ExternalWalletNotFound = 101,
    AggregatedBlsKeyNotFound = 109,
    WebKeysNotFound = 111,
    FactoryNotFound = 113,
    VersionNotFound = 117,
    AlreadyInitialized = 410,
    // TokenAlreadySupported = 411,
    // TokenNotSupported = 413,
    // OracleNotFound = 415,
    // ChainNotFound = 417,
    // ReceptacleNotFound = 419,
    // TransferNotFound = 421,
    // NodeNotFound = 437,
    // TokenChainMapNotFound = 439,
    // BridgeNotFound = 433,
    // NotAllowedOracle = 423,
    // NotAllowedChain = 425,
    // PlatformNotSupported = 441,
    UsernameAlreadyRegistered = 443,
    UsernameNotRegistered = 445,
    PasskeyAlreadyLinked = 447,
    PasskeyNotLinked = 449,
    // InvalidToken = 427,
    // InvalidReceiverAddress = 429,
    // AlreadyNodeOperator = 505,
    // ChainAlreadyAdded = 511,
    // MessageAlreadyProcessed = 521,
    // ExceedsLiquidity = 610,
    // RebalanceThresholdNotReached = 710,
    // RebalanceAmountOutOfRange = 711,
    // NothingToRebalance = 713,
    // AlreadyLatest = 717,
    ExceedMaxAllowance = 719,
    // EmptyTokenList = 721,
    InvalidLimit = 723,
    OwnerNotSet = 727,
    InvalidAmount = 729,
    InvalidExpiration = 731,
    InvalidNonce = 733,
    InvalidInvokeContract = 735,
    InvalidInvokeFunction = 737,
    TooManyKeys = 739,
    // Overflow = 741,
    UpperNotAllowed = 743,
    MaxLengthExceeded = 745,
    WalletNotFound = 747,
}
